POST http://localhost:6000/register
Content-Type: application/json

{
  "username": "user",
  "password": "user",
  "email": "test@test.ca"
}

###

POST http://localhost:6000/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "email": "admin@test.ca",
  "is_admin": true
}

###

POST http://localhost:6000/login
Content-Type: application/json

{
  "username": "user",
  "password": "user"
}


###
POST http://localhost:6000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


###
GET http://localhost:6000/logout
Content-Type: application/json


###
GET http://localhost:5000/api/v1/pokemon/808
auth_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzc1Y2E4YjMzMWExZmVlYzQ3Y2FiMTUiLCJpYXQiOjE2Njg2NjQxMTR9.T1NwEWVM7QYMXEZDbRoCiRp4Vdgw723oaxN3-9VUZsw

###
GET http://localhost:5000/api/v1/pokemonImage/1
auth_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzc1YjFjMWIzMDI5OTYyNjI1ZmVjMjciLCJpYXQiOjE2Njg2NjIyMDl9.qCDIYZgZsG9SgqUsC_VmbOe2_O72wK0DG7L_6XgewAM


###
PATCH  http://localhost:5000/api/v1/pokemon/1
auth_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzc1YjFjMWIzMDI5OTYyNjI1ZmVjMjciLCJpYXQiOjE2Njg2NjMzNjZ9.-Q6YdaLqDw1F-jmPmh5gPPcAudZBp4_fJZz_eU1jyQM
Content-Type: application/json

{
    "name": {
      "english": "test",
      "japanese": "test",
      "chinese": "test",
      "french": "test"
    },
    "base": {
      "HP": 60,
      "Attack": 20,
      "Defense": 55,
      "Speed": 30,
      "Speed Attack": 25,
      "Speed Defense": 25
    },
    "id": 1000,
    "type": [
      "Bug"
    ],
    "__v": 0
}

###
DELETE http://localhost:5000/api/v1/pokemon/777
auth_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzc1YjFjMWIzMDI5OTYyNjI1ZmVjMjciLCJpYXQiOjE2Njg2NjMzNjZ9.-Q6YdaLqDw1F-jmPmh5gPPcAudZBp4_fJZz_eU1jyQM
